name: Deploy python app to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO_NAME: gcp_deploy_project
  IMAGE_NAME: python-app
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  build:
    name: Build&Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest bandit

      - name: security scan
        run: bandit -r . || true

  containerize:
    name: Build Docker image and push image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Authenctication to GCP_PROJECT_ID
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
        
      - name: Configure Docker for artifcat
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev
      
      - name: Build Docker image
        run: |
          docker buildx build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest
      
      - name: Push image to registry
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest